name: Simple Package — Sequential macOS arm64 & Windows x64

on:
  workflow_dispatch: # you can also manually trigger this workflow
  push:
    branches:
      - main

jobs:
  build-macos-arm64:
    name: Build macOS arm64
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Show runner arch
        run: uname -m || true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with PyInstaller (macOS arm64)
        run: |
          pyinstaller --onefile app/hello.py -n hello-macos-arm64
      - name: Debug dist
        run: ls -la dist || true
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-macos-arm64
          path: dist/hello-macos-arm64

  build-windows-x64:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with PyInstaller (Windows x64)
        shell: pwsh
        run: |
          pyinstaller --onefile app/hello.py -n hello-windows-x64
      - name: Debug dist
        shell: pwsh
        run: dir dist || true
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-windows-x64
          path: dist/hello-windows-x64.exe
